.TH "oradba\-exec\-sql" "1" "13/12/2013" "Пользовательские команды" "Пользовательские команды"
.SH "НАЗВАНИЕ"
oradba\-exec\-sql \- Выполнить произвольную SQL\-команду или SQL\-скрипт в базе данных Oracle\.
.SH "СИНТАКСИС"
.HP
\fBoradba\-exec\-sql\fR [\fI\-\-database DB\fR] [\fI\-\-user DB_USER\fR] [\fI\-\-password PWD\fR]
         [\fI\-\-log\-dir LOGDIR\fR] [\fI\-\-log\-name LOGNAME\fR] [\fI\-\-log\-mode LOGMODE\fR]
         \fI"SQL\-запрос|SQL\-Скрипт"\fR [\fIАргумент1 Аргумент2 \.\.\.\fR]
.SH "ОПИСАНИЕ"
Программа \fBoradba\-exec\-sql\fR используется для выполнения произвольной SQL\-команды или SQL\-скрипта
в базах данных Oracle\. Программа \fBoradba\-exec\-sql\fR предназначена для упрощения и унификации запуска
периодических SQL\-команд посредством службы \fBcron\fR(8)\.
.PP
Работа программы \fBoradba\-exec\-sql\fR настраивается с помощью файла конфигурации \fI/etc/oradba/oradba\-exec\-sql.conf\fR\.
.PP
Программа \fBoradba\-exec\-sql\fR создана для упрощения основных действий, необходимых при выполнении 
произвольной SQL\-команды в базе данных Oracle, а именно:
.PP
.RS
* подключение в целевую базу данных;
.br
* безопасное хранение паролей подключения в \fBOracle Password Repository\fR;
.br
* централизованное хранение и ротация лог\-файлов работы SQL\-команд\.
.RE
.SH "ПАРАМЕТРЫ"
.SS "Обязательные параметры"
.TP
\fB\-u\fR, \fB\-\-user\fR DB_USER
Пользователь для подключения в БД\. Данный параметр обязательно должен быть задан в коммандной строке или в файле конфигурации\.
.SS "Необязательные параметры"
.TP
\fB\-p\fR, \fB\-\-password\fR DB_PWD
Переопределить пароль для доступа в базу данных. По умолчанию, пароли доступа в базу данных хранятся в специальном
репозитарии паролей \- \fBOracle Password Repository\fR, который сопровождается с помощью утилиты \fBopr\fR\(8)\.
.TP
\fB\-b\fR, \fB\-\-database\fR DB
TNSAlias целевой базы данных для подключения\. По умолчанию \- \fIlocal\fR\.
.TP
\fB\-l\fR, \fB\-\-log\-name\fR LOGNAME
Имя журнального файла для вывода результатов работы\. По умолчанию имя журнального лог\-файла генерируется автоматически\. Файлы создаются в каталоге \fBLOGDIR\fR\.
.TP
\fB\-r\fR, \fB\-\-log\-dir\fR LOGDIR
Каталог для хранения журнальных файлов\. По умолчанию \fI/var/log/oradba/exec\-sql\fR\.
.TP
\fB\-o\fR, \fB\-\-log\-mode\fR LOGMODE
Режим вывода в журнальный файл (по умолчанию \fIauto\fR):
.RS
.IP
runit  \- с использованием службы логгирования \fBRunIt\fR;
.br
dtools \- с использованием службы логгирования \fBDaemonTools\fR;
.br
syslog \- с использованием службы логгирования \fBSysLog\fR;
.br
file   \- вывод в файл, ротация осуществляется с помощью службы \fBLogRotate\fR\.
.RE
.IP
Режим вывода определяется автоматически, либо может быть задан явно в файле конфигурации или командной строке\.
.HP
\fBSQL\-запрос\fR \- Текст SQL\-запроса для выполнения в БД
.HP
\fBSQL\-скрипт\fR \- Файл SQL\-скрипта для выполнения в БД
.IP
[Аргумент1 Аргумент2 \.\.\.] \- необязательные аргументы для SQL\-скрипта
.SH "КОНФИГУРАЦИЯ"
.PP
Параметры конфигурации задаются в файле \fI/etc/oradba/oradba\-exec\-sql.conf\fR\.
.TP
\fBDB\fR
Целевая база данных для работы\.
.TP
\fBDB_USER\fR
Пользователь, от имени которого выполняется SQL\-скрипт или SQL\-команда\.
.TP
\fBNLS_LANG\fR
Задать локализацию при выполнении SQL\-команд\.
.TP
\fBLOG_FILE\fR
Лог\-файл по умолчанию\.
.TP
\fBLOG_MODE\fR
Принудительный режим вывода в лог\-файлы\.
.TP
\fBLOG_DIR\fR
Базовый каталог для хранения журнальных файлов\.
.TP
\fBOLD_LOG_KEEP_DAYS\fR
Время хранения копий старых журнальных файлов, в днях
.SH "ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ"
.TP
\fBORACLE_HOME\fR
Каталог установки программного обеспечения СУБД Oracle\.
.TP
\fBDB_APPINFO\fR
Строка идентификации сессии приложения в базе данных\.
.TP
\fBDB\fR
TNSAlias базы данных для доступа\.
.TP
\fBDB_USER\fR
Пользователь для подключения в базу данных\.
.TP
\fBDB_PWD\fR
Пароль для подключения в базу данных\.
.TP
\fBOPR\fR
Программа доступа к репозитарию паролей Oracle\.
.TP
\fBSQLPLUS_FORMAT\fR
Пользовательский файл для форматирования вывода SQL\-запросов\.
.TP
\fBLOG_DIR\fR
Базовый каталог журнальных файлов работы SQL\-запрсов\.
.SH "ПРИМЕРЫ ИСПОЛЬЗОВАНИЯ"
.SS "Запуск SQL из cron"
.IP
*/5 * * * * /usr/bin/oradba\-exec\-sql "select 1 from dual"
.RS
.IP
Каждые 5 минут будет выполнятся команда \fIselect 1 from dual\fR\. Параметры подключения (база данных, пользователь
для подключения) читаются из файла конфигурации \fI/etc/oradba/oradba\-exec\-sql.conf\fR\. Журнал выполнения создаётся
в каталоге \fB/var/log/oradba/exec\-sql\fR\. Если задан режим вывода в файл \fILOG_MODE=file\fR, то будет автоматически
генерироваться имя лог\-файла \fIselect_1_from_dual\fR\.
.RE
.IP
*/5 * * * * /usr/bin/oradba\-exec\-sql \-\-user TEST \-\-log\-name my\-log "select 1 from dual"
.RS
.IP
Каждые 5 минут будет выполнятся команда \fIselect 1 from dual\fR от имени пользователя \fBTEST\fR\. Параметры подключения (база данных)
читаются из файла конфигурации \fI/etc/oradba/oradba\-exec\-sql.conf\fR\. Журнал выполнения создаётся
в каталоге \fB/var/log/oradba/exec\-sql/my\-log\fR, в режимах \fIrunit\fR или \fIdtools\fR; в виде файла 
\fB/var/log/oradba/exec\-sql/my\-log\.log\fR в режиме \fIfile\fR\, либо записывается в системные журналы в режиме \fIsyslog\fR.
.RE
.SS "Запуск из командной строки"
.IP
/usr/bin/oradba\-exec\-sql \-\-user test \-\-password test \-\-database TEST \-\-log\-dir /tmp \-\-log\-name test \-\-log\-mode file "select 1 from dual"
.IP
Результат работы команды будет помещён в лог\-файл \fB/tmp/test\fR\.
.SH "АВТОР"
.PP
Кряжевских Сергей, <soliverr@gmail.com>
.SH "ФАЙЛЫ"
.TP
\fI/etc/oradba/oradba\-exec\-sql.conf\fR
Содержит параметры для работы программы \fBoradba\-exec\-sql\fR\.
.TP
\fI/etc/oradba/sqlfunctions.def\fR
Содержит команды форматирования и управления выводом для Oracle SQLPlus\.
.TP
\fI/var/log/oradba/exec\-sql/oradba\-exec\-sql.log\fR
Главный журнальный файл, содержащий историю запуска программы \fBoradba\-exec\-sql\fR\. В данный файл записываются
сообщения, если их невозможно поместить в указанный параметрами \fI\-\-log\-dir\fR и \fI\-\-log\-name\fR файл\.
.TP
\fI/var/log/rias/oradba\-exec\-sql\fR
Каталог хранения журнальных файлов работы SQL\-команд или SQL\-скриптов, если не переопределён через параметр
\-\-log\-dir или параметр файла конфигурации \fILOG_DIR\fR\.
.SS "Общий доступ к журнальным файлам"
.PP
При работе в режиме записи журнальных файлов \fIrunit\fR или \fIdtools\fR нельзя использовать один и тот же
журнальный файл при работе от нескольких пользователей системы\.
.PP
При работе в режиме записи журнальных файлов \fIfile\fR необходимо обеспечить право записи в журнальный файл
для всех пользователей, которым необходимо выполнять SQL\-команду и записывать результаты исполнения в один и
тот же журнальный файл\.
.SH "ОШИБКИ"
.PP
Об ошибках сообщайте через систему контроля ошибок \fBhttp://sourceforge.net/oracledba\fR\.
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBopr\fR(8)
