.TH "rias_exec_sql" "1" "05/04/2010" "User commands" "User commands"
.SH "NAME"
rias_exec_sql \- Execute a SQL-query or a SQL-file in billing databases\.
.SH "SYNOPSIS"
.HP
\fBrias_exec_sql\fR [\fI\-\-user DB_USER\fR] [\fI\-\-password PWD\fR] [\fI\-\-database DB\fR]
       [\fI\-\-log-name LOGNAME\fR] [\fI\-\-log-mode LOGMODE\fR] [\fI\-\-log-dir LOGDIR\fR]
       \fI"SQL-query|SQL-file"\fR [\fIArg1 \.\.\.\fR]
.SH "DESCRIPTION"
\fBrias_exec_sql\fR should be used to execute a SQL-query or SQL-file in billing databases\. \fBrias_exec_sql\fR commonly used in \fBcron\fR(8) tasks\.
.PP
\fBrias_exec_sql\fR has configuration in file \fI/opt/rias/etc/rias_exec_sql.conf\fR\.
.PP
\fBrias_exec_sql\fR simplifies common actions while execute SQL-query:
.PP
.RS
* connect to the target database;
.br
* safety storage database passwords in \fBOracle Password Repository\fR;
.br
* centarlized storage and rotation log-file of executing SQL-queries\.
.RE
.SH "OPTIONS"
.SS "Mandatory options"
.TP
\fB\-u\fR, \fB\-\-user\fR DB_USER
Database user to conect to\. This option should be present in configuration file or as command line option\.
\fI/opt/rias/etc/rias_exec_sql.conf\fR\.
.SS "Optional options"
.TP
\fB\-p\fR, \fB\-\-password\fR DB_PWD
Database password to connect to. Database passwords keeps in password repository \- \fBOracle Password Repository\fR, which mantains with \fBopr\fR\(8) utility\.
.TP
\fB\-b\fR, \fB\-\-database\fR DB
TNSAlias of target database\. Default is \fIlocal\fR\.
.TP
\fB\-l\fR, \fB\-\-log\-name\fR LOGNAME
Name of log\-file\. Default is autogenerate\. Logfiles created in LOGDIR.
.TP
\fB\-r\fR, \fB\-\-log\-dir\fR LOGDIR
Directory to keep logfiles\. Default is \fI/opt/rias/log/rias_exec_sql\fR\.
.TP
\fB\-o\fR, \fB\-\-log\-mode\fR LOGMODE
Select logger mode (default \fIauto\fR):
.RS
.IP
runit  \- svlogd from \fBRunIt\fR;
.br
dtools \- multilog from \fBDaemonTools\fR;
.br
syslog \- logger for \fBSysLog\fR;
.br
file   \- plain logfile with \fBLogRotate\fR rotation\.
.RE
.IP
Logger mode detects automatically or can be setted in configuration file or as comman line option\.
.HP
\fBSQL\-query\fR \- SQL\-query to execute in a target database
.HP
\fBSQL\-скрипт\fR \- SQL\-file to execute in a target database
.IP
[Arg1 Arg2 \.\.\.] \- optional argumants for SQL\-file
.SH "CONFIGURATION"
.PP
Configuration paramaters stored in file \fI/opt/rias/etc/rias_exec_sql.conf\fR\.
.TP
\fBDB\fR
Target database\.
.TP
\fBDB_USER\fR
Database user to connect to.
.TP
\fBNLS_LANG\fR
Oracle NLS parameters\.
.TP
\fBLOG_FILE\fR
Log\-file\.
.TP
\fBLOG_MODE\fR
Logger mode\.
.TP
\fBLOG_DIR\fR
Logdir\.
.TP
\fBOLD_LOG_KEEP_DAYS\fR
Keep old log\-files in days\.
.SH "ENVIRONMENTS"
.TP
\fBORACLE_HOME\fR
Oracle home\.
.TP
\fBDB_APPINFO\fR
Session identifier in database\.
.TP
\fBDB\fR
TNSAlias of database to connect to\.
.TP
\fBDB_USER\fR
Database user to connect to\.
.TP
\fBDB_PWD\fR
Database password to connect to\.
.TP
\fBOPR\fR
Excutables to access to Oracle Password Repository\.
.TP
\fBSQLPLUS_FORMAT\fR
User's file to format SQLPlus output\.
.TP
\fBLOG_DIR\fR
Base directory for logfiles\.
.SH "EXAMPLES"
.SS "Execute SQL in cron"
.IP
*/5 * * * * /opt/rias/bin/rias_exec_sql "select 1 from dual"
.RS
.IP
Logname is generated as select_1_from_dual
.RE
.IP
*/5 * * * * /opt/rias/bin/rias_exec_sql \-\-user TEST \-\-log\-name my\-log "select 1 from dual;"
.RS
.IP
Logname my\-log
.RE
.SS "Execute in command line"
.IP
/opt/rias/bin/rias_exec_sql \-\-user test \-\-password test \-\-database TEST \-\-log\-dir /tmp \-\-log\-name test \-\-log\-mode file "select 1 from dual"
.IP
Result will output in file /tmp/test\.
.SH "AUTHOR"
.PP
Kryazhevskikh Sergey, oliver@ertelecom.ru
.SH "FILES"
.TP
\fI/opt/rias/etc/rias_exec_sql.conf\fR
Configuration parameters for \fBrias_exec_sql\fR\.
.SH "BUGS"
.PP
Erros should be reported through ITS \fBhttp://redmine.ertelecom.ru\fR\.
.SH "SEE ALSO"
.PP
\fBopr\fR(8)
